index:
    path: /
    controller: App\Controller\DefaultController::index
Index:
    path: /index
    controller: App\Controller\DefaultController::index
Login:
    path: /login
    controller: App\Controller\SecurityController::login
Register:
    path: /register
    controller: App\Controller\RegistrationController::register
RegisterAdmin:
    path: /registeradmin
    controller: App\Controller\RegistrationController::registeradmin
AddDestinationPage:
    path: /destination/add
    controller: App\Controller\DestinationController::addDestination
Update_destination:
    path: /destination/update
    controller: App\Controller\DestinationController::update_destination